### PR TITLE
Update ! LIST.md

### PR DESCRIPTION
**Pull request by ArcerionDev**
72 is not really consequential as we don't know what it comes from, but it's worth adding

### CODE REVIEW

**Comment by ArcerionDev** [comment]
citation for code 84

image

**Comment by afkvido** [comment]
> 72 is not really consequential as we don't know what it comes from, but it's worth adding

yeah

**Review by afkvido — APPROVED** [review]
hell yea!

**Comment by afkvido** [comment]
arcy may I add you as a collab? @ArcerionDev

**Comment by donaldli2020** [comment]
this pr failed the "check" thing 😢

**Comment by afkvido** [comment]
> this pr failed the "check" thing 😢

it was a bug with github greetings

**Comment by donaldli2020** [comment]
also, the #2 has broken links

**Comment by afkvido** [comment]
> also, the #2 has broken links

oh shit- imma fix that, ty for reminding me

**Comment by afkvido** [comment]
done

**Pull request merged**
