### PR TITLE
Update ! LIST.md

### PR DESCRIPTION
**Pull request by donaldli2020**
The discussions tab doesn't exist

### CODE REVIEW

**Comment by afkvido** [comment]
Thanks, gimme a min :)

**Comment by afkvido** [comment]
A system token login causes 20?

**Comment by afkvido** [comment]
Also, what was the error code caused by opening the console/inspect in prodigy?

**Review by afkvido — APPROVED** [review]
yes

**Comment by afkvido** [comment]
gg on your contrib role, u deserve it :)

**Comment by donaldli2020** [comment]
> Also, what was the error code caused by opening the console/inspect in prodigy?

They got rid of it, 404

**Comment by afkvido** [comment]
> They got rid of it, 404

thank god they got rid of it.
attempting to hide the javascript console/inspect element can be seen as very malicious intentions, because trying to hide code running on the computer = sussy

**Pull request merged**
