### PR TITLE
Happens with the Dashboard too!

### PR DESCRIPTION
**Pull request by eris-webserv**
Watch it, cheating them in on Dashboard does it too.

### CODE REVIEW

**Review by afkvido — CHANGES_REQUESTED** [review]
pls change

`Spawning in OG epic buddies with WCM/PHEX or the dashboard.`

**Review by afkvido — APPROVED** [review]
should be good now, thanks for reminding me ant this

**Comment by afkvido** [comment]
Thanks for contributing @Erisfiregamer1!

**Comment by eris-webserv** [comment]
:D

**Pull request merged**
