### PR TITLE
grammar and spelling

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Comment by afkvido** [comment]
Seems good to me. I also added your credit at the bottom.

Thanks!

**Comment by donaldli2020** [comment]
Oops! It is not January 19 unless you are in East Asia!

**Comment by afkvido** [comment]
> Oops! It is not January 19 unless you are in East Asia!

it is in fact January 18, I thought you were in East Asia.

**Comment by donaldli2020** [comment]
I am in Eastern Standard Time (11:42 AM)

**Comment by afkvido** [comment]
> I am in Eastern Standard Time (11:42 AM)

I am pacific tiem, 8:44 am

**Pull request merged**
