### PR TITLE
it's gone

### PR DESCRIPTION
**Pull request by eris-webserv**
PMGH died :skull:
fuck prodigy

### CODE REVIEW

**Comment by afkvido** [comment]
prodigy is so cheap that they hired a lawyer to dmca PMGH instead of hiring a developer to write good code

**Comment by eris-webserv** [comment]
I support ProdigyPNP
screw prodigy
(If you get the hacks working again I will provide a server to host P-NP on :trollface: )

**Comment by eris-webserv** [comment]
wait a minute, that commit was on my fork

**Comment by afkvido** [comment]
> wait a minute, that commit was on my fork

yup lmao

**Comment by afkvido** [comment]
> I support ProdigyPNP

thanks! would u like me to invite you to the org?

<br><br>



> screw prodigy

fr, screw the p2w game that hires DMCA lawyers instead of good devs.
YO PRODIGY, Y'ALL SHOULD HIRE MUSTAN, ARCERION, AND BOREDFISH

<br><br>


> (If you get the hacks working again I will provide a server to host P-NP on :trollface: )

oh hell yea, tysm!

**Comment by eris-webserv** [comment]
> > I support ProdigyPNP
> 
> thanks! would u like me to invite you to the org?
>
yes
> > screw prodigy
> 
> fr, screw the p2w game that hires DMCA lawyers instead of good devs. YO PRODIGY, Y'ALL SHOULD HIRE MUSTAN, ARCERION, AND BOREDFISH
> 
hell yeah then the game would have half-decent security and not get hacked by a DASHBOARD (which, btw, hosted's dashboard is still up and working)
> > (If you get the hacks working again I will provide a server to host P-NP on :trollface: )
> 
> oh hell yea, tysm!

DM me (Eris#0521), I'll set it up for you (using the P-NP build from ProdigyPNP)

**Comment by donaldli2020** [comment]
im working on the pnp and having trouble finding a server
no hosting websites work

**Comment by eris-webserv** [comment]
> im working on the pnp and having trouble finding a server no hosting websites work

Have you tried the oracle cloud? Sure, you do need a valid credit card (NO PREPAID), but the 3 servers you can get are very useful, especially the ARM one.
Also, P-NP :B:roke.

**Comment by donaldli2020** [comment]
it says i get 300 free credit
when i select canada
it says i get 400 free credit
that's 318.21 dollars usa

**Comment by donaldli2020** [comment]
lmao

**Comment by afkvido** [comment]
y'all can just use DigitalOcean 

##### (redwhisper be like: `mmm digitalocean`)

**Comment by donaldli2020** [comment]
ok

**Comment by donaldli2020** [comment]
I don't have credit card to PayPal!

**Comment by afkvido** [comment]
dw abt it, i'll handle that

**Pull request merged**
