### PR TITLE
fix date and add another error

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Review by afkvido — APPROVED** [review]

**Comment by afkvido** [comment]
@donaldli2020 I added you as a collaborator, check your email!

**Comment by donaldli2020** [comment]
I checked my notifications.

**Comment by donaldli2020** [comment]
I saw the invitation

**Comment by afkvido** [comment]
> I saw the invitation

ayyy, you're a collab now :)

gg

**Comment by afkvido** [comment]
well, now you can commit directly and add the Official label to your PRs

**Pull request merged**
